#!/usr/bin/env python3
"""Phase 4 extension: dense-chain instances at n=17 and n=18.

Extends the recorded mechanics benchmark suite (phase 4) with four new cases
of the dense-influence family -- dense-chain at 17 and 18 springs, both
observation variants -- generated by the recorded ``run_case`` driver of
``mechanics_benchmarks.py`` with the same settings used for the recorded
dense-chain cases (full relation enumeration, no relation cap, deterministic
minimum-fill decomposition, certified DP, policy reconstruction).

Each case is generated in its own invocation (--case) so that the largest
certificate emissions cannot be lost to a session-terminating environment;
--assembles the per-case records into
``reports/mechanics_dense_extension.json``.
"""
from __future__ import annotations

import argparse
import json
import platform
import sys
import time
from pathlib import Path

PROTO = Path(__file__).resolve().parent
sys.path.insert(0, str(PROTO))

from mechanics_benchmarks import run_case  # noqa: E402

EXT_CASES = [
    ("dense-chain", 17, "same"),
    ("dense-chain", 17, "split"),
    ("dense-chain", 18, "same"),
    ("dense-chain", 18, "split"),
]


def case_path(family: str, size: int, obs: str) -> Path:
    key = f"{family}_{size}_{obs}".replace("dense-chain", "dense")
    return PROTO / "reports" / f"dense_ext_gen_{key}.json"


def hardware_info() -> dict:
    import resource
    uname = platform.uname()
    total = Path("/proc/meminfo").read_text().splitlines()[0].split()[1]
    return {
        "cpu": uname.processor or uname.machine,
        "cores": 2,
        "ram_total": f"{int(total) / 1024 / 1024:.1f}Gi",
        "os": "glibc " + platform.libc_ver()[1],
        "kernel": uname.release,
        "machine_python": platform.python_version(),
        "note": "wall-clock timings are whole-process; machine is a shared two-core virtual machine",
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", help="family|size|obs, e.g. dense-chain|17|same")
    ap.add_argument("--assemble", action="store_true")
    args = ap.parse_args()

    if args.case:
        family, size, obs = args.case.split("|")
        size = int(size)
        t0 = time.perf_counter()
        entry = run_case(family, size, obs, f"examples/mech_dense{size}_{obs}")
        entry["generation_wall_seconds"] = round(time.perf_counter() - t0, 4)
        out = case_path(family, size, obs)
        out.write_text(json.dumps(entry, indent=2))
        print(json.dumps({k: entry.get(k) for k in (
            "family", "size", "observation", "fe_verify_status",
            "decomp_verify_status", "dp_type", "dp_status",
            "dp_verify_status", "policy_verify_status",
            "decomposition_width", "relation_max", "row_batch_bytes",
            "instance_bytes", "dp_certificate_bytes",
            "generation_wall_seconds")}, indent=2))
        return

    if args.assemble:
        cases = []
        missing = []
        for family, size, obs in EXT_CASES:
            key = f"{family}_{size}_{obs}".replace("dense-chain", "dense")
            p = PROTO / "reports" / f"dense_ext_gen_{key}.json"
            pf = PROTO / "reports" / f"dense_ext_gen_{key}_FAILED.json"
            if p.exists():
                cases.append(json.loads(p.read_text()))
            elif pf.exists():
                cases.append(json.loads(pf.read_text()))
            else:
                missing.append(f"{family}|{size}|{obs}")
        solved = [c for c in cases if c.get("dp_verify_status") == "VERIFIED"]
        out = {
            "status": "COMPLETE",
            "phase": "4-extension dense-chain n=17,18",
            "protocol": {
                "driver": "mechanics_benchmarks.run_case (recorded phase 4 driver, unchanged)",
                "relation_enumeration": "full (no relation cap), matching the recorded dense-chain cases",
                "decomposition": "deterministic minimum-fill elimination, validated by the tree-decomposition verifier",
                "hardware": hardware_info(),
                "note": "extension of the recorded phase 4 suite beyond the recorded dense-family boundary n=16; per-case generation is checkpointed because the environment terminates long-running sessions",
            },
            "families": {
                "dense-chain": "grounded mass-spring chain, node-force actuators, monitored mid-chain displacement (dense influence)",
            },
            "cases": cases,
            "missing_cases": missing,
            "summary": {
                "cases": len(cases),
                "row_batches_verified": sum(1 for c in cases if c.get("fe_verify_status") == "VERIFIED"),
                "decompositions_verified": sum(1 for c in cases if c.get("decomp_verify_status") == "VERIFIED"),
                "dp_certificates_verified": sum(1 for c in cases if c.get("dp_verify_status") == "VERIFIED"),
                "policies_verified": sum(1 for c in cases if c.get("policy_verify_status") == "VERIFIED"),
                "refutations_certified": sum(1 for c in cases if c.get("dp_type") == "DP-REFUTATION"),
                "dp_memory_limit_cases": sum(1 for c in cases if c.get("instance_status") == "DP-MEMORY-LIMIT"),
                "missing_cases": len(missing),
            },
        }
        (PROTO / "reports" / "mechanics_dense_extension.json").write_text(
            json.dumps(out, indent=2))
        print(json.dumps(out["summary"], indent=2))
        return

    ap.error("specify --case family|size|obs or --assemble")


if __name__ == "__main__":
    main()
